
# Increase max upload size from 5MG to 100MB: https://stackoverflow.com/questions/18037737/how-to-change-maximum-upload-size-exceeded-restriction-in-shiny-and-save-user
options(shiny.maxRequestSize=100*1024^2)

function(input, output, session) {
    
    ## Globals ----
    
    full_df <- reactiveVal(NULL)
    loaded_files   <- reactiveVal(character(0))  # tracks file names for the UI list
    
    # Keep track of which normalizations have been done on this dataset. (Updates when dataset changes.)
    completed_normalizations <- reactiveVal(character(0))
    
    
    
    ## 1. Data management ----

    ### 1.0 File upload UI ----
    output$file_upload_ui <- renderUI({
        switch(input$data_source,
            "DARLA" = tagList(
                fileInput("uploaded_data", "Upload a .csv file generated by DARLA",
                          multiple = FALSE,
                          accept = c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
                p("This should be the file originally called \"formants.csv\" that",
                  tags$a("DARLA", href = "http://darla.dartmouth.edu", target = "_blank"),
                  "emailed to you. (The file you upload can be named whatever you want.)")
            ),
            "new-fave" = tagList(
                fileInput("uploaded_data", "Upload a .csv file generated by new-fave",
                          multiple = FALSE,
                          accept = c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
                p("This should be the file that originally had \"_tracks.csv\" in the name that",
                  tags$a("new-fave", href = "https://forced-alignment-and-vowel-extraction.github.io/new-fave/", target = "_blank"),
                  "generated for you. (The file you upload can be named whatever you want.)")
            ),
            "sample" = tagList(
                p("Data loaded. You may now process the data by clicking the button below."),
                p("This is a sample of Joey Stanley's vowels and is available in the",
                  tags$a("joeysvowels", href = "https://joeystanley.github.io/joeysvowels/", target = "_blank"),
                  "package on Github.")
            )
        )
    })

    ### 1.1 Loading data ----
    observeEvent(input$process_uploaded_button, {

        # Determine the filename before doing anything else so we can check for duplicates.
        this_file_name <- if (input$data_source == "sample") {
            "joey_darla.csv"
        } else {
            req(input$uploaded_data)
            input$uploaded_data$name
        }

        # Guard against loading the same file twice.
        if (this_file_name %in% loaded_files()) {
            showNotification(
                ui       = paste0('"', this_file_name, '" is already loaded. Remove it first if you want to reload it.'),
                type     = "warning",
                duration = 5
            )
            return()
        }

        withProgress(message = "Activating air compressor…",
                     detail = "This may take a few seconds.",
                     value = 0,
                     {
                         incProgress(1/4, detail = "Reading file…")
                         # Get the data path. If uploaded, then pull from there. If sample, then pull from local data.
                         if (input$data_source == "sample") {
                             path_to_data <- "data/joey_darla.csv"
                         } else {
                             path_to_data <- input$uploaded_data$datapath
                         }
                         
                         # Don't crash if darla data is uploaded with the new-fave button and vice versa
                         tryCatch({
                             raw <- read_csv(path_to_data, show_col_types = FALSE) |> 
                                 # keep source file to allow for removing later on
                                 mutate(source_file = this_file_name) 
                             
                             # Prep data according to data source.
                             incProgress(1/4, detail = "Prepping data…")
                             cleaned <- if (input$data_source == "new-fave") {
                                 prep_newfave_data(raw)
                             } else {
                                 prep_darla_data(raw)
                             }
                             
                             incProgress(1/4, message = "Pulling out all the stops", detail = "Step 1: Coding allophones…")
                             ooo1 <- ooo1_code_allophones(cleaned)
                             
                             incProgress(1/4, detail = "Step 2: Removing outliers… (Note: this is the most time consuming step)")
                             ooo2 <- ooo2_remove_outliers(ooo1)
                             
                             # Save/add to the new datasets
                             if (is.null(full_df())) {
                                 full_df(ooo2)
                             } else {
                                 full_df(bind_rows(full_df(), ooo2))
                             }
                             loaded_files(c(loaded_files(), this_file_name))
                             
                             # Strip any previously normalized columns so they get recomputed fresh
                             full_df(full_df() |> select(-matches("F[1234]_[a-z]+$")))
                             # After adding data, reset what normalization procedures have been done.
                             completed_normalizations(character(0))
                             
                         }, error = function(e) {
                             showNotification(
                                 ui       = paste("Processing failed. Please check that your data source selection (e.g. DARLA vs. new-fave)",
                                                  "matches the file you uploaded.",
                                                  "\nIf the problem persists, the error was:", conditionMessage(e)),
                                 type     = "error",
                                 duration = NULL   # stays until user dismisses it
                             )
                         })
                     })
    })
    
    # Update the "process" button label dynamically
    observe({
        label <- if (is.null(full_df())) "Process my data" else "Process and add to existing data"
        updateActionButton(session, "process_uploaded_button", label = label)
    })
    
    # Update the list of speakers whenever the full dataset changes.
    observe({
        req(full_df())
        list_of_speakers <- full_df() |> pull(speaker_id) |> unique()
        
        # Keep current selection of speakers if it's still valid, otherwise default to first
        current_selection <- isolate(input$speaker_selection)
        still_valid <- intersect(current_selection, list_of_speakers)
        new_selection <- if (length(still_valid) > 0) still_valid else head(list_of_speakers, 1)
        
        updateSelectInput(session, "speaker_selection",
                          choices  = list_of_speakers,
                          selected = new_selection)
        
    })

    
    ### 1.2 Removing data ----
    observeEvent(input$remove_data_button, {
        
        to_remove <- input$selected_for_removal %||% character(0)
        req(length(to_remove) > 0)
        
        remaining <- setdiff(loaded_files(), to_remove)
        loaded_files(remaining)
        
        if (length(remaining) == 0) {
            # explicitly NULL when last dataset removed
            full_df(NULL)  
        } else {
            
            full_df(full_df() |>
                        # Re-filter the data to only keep rows from remaining files
                        filter(source_file %in% remaining) |>
                        # Strip any previously normalized columns so they get recomputed fresh
                        select(-matches("F[1234]_[a-z]+$")) |>
                        # Drop columns that are entirely NA — can happen when e.g. new-fave data
                        # (which has F3) is removed and only DARLA data (no F3) remains.
                        select(where(\(x) !all(is.na(x)))))
            
        }
        
        # After removing data, reset what normalization procedures have been done.
        completed_normalizations(character(0))
    })
    
    # Render the dynamic checklist of loaded files
    output$loaded_datasets_list <- renderUI({
        files <- loaded_files()
        if (length(files) == 0) {
            p("No datasets loaded yet.", style = "color: gray;")
        } else {
            checkboxGroupInput("selected_for_removal",
                               label = NULL,
                               choices = files,
                               selected = NULL)
        }
    })
    
    
    ## 2. Data processing ----
    
    ### 2.0 Subsets -----
    
    # Create just a midpoints df.
    midpoints_df <- reactive({ 
        req(full_df())
        
        full_df() |> 
            ooo4_filter_otherwise_good_data() |>
            filter(prop_time > 0.4,
                   prop_time < 0.6) |>

            # Matches("F[1234]") intentionally catches both raw (F1, F2) and normalized (F1_lm, F2_z, etc.) columns.
            # Midpoints are computed for all of them.
            summarize(across(matches("F[1234]"), \(x) mean(x, na.rm = TRUE)),
                      # `.by` uses negative selection to "group by everything except time and formant columns",
                      # i.e. collapse prop_time into a single row per token.
                      # All I need is token_id, and the rest are "passed on" so that they're available for later processing.
                      .by = -c(prop_time, time, matches("F\\d")))
    })
    
    # Create a trajectory df. Same as the normed df, but here for clarity.
    # TODO: Trajectories
    # trajectories_df <- reactive({ full_df() |>  ooo4_filter_otherwise_good_data() })
    
    
    
    ### 2.1 Normalization (ooo3) ----
    # Lives here rather than in processing.R because it needs to cache results
    # per normalization method and respond to user input (see ooo3 note in processing.R).
    observe({
        req(full_df())
        req(nrow(full_df()) > 0)

        method <- input$norm_method

        # "none" needs no transformation — alias directly to the raw formants.
        if (method == "n") {
            full_df(full_df() |> mutate(F1_norm = F1, F2_norm = F2))
            return()
        }

        info <- norm_methods[[method]]

        # Only run normalization if we haven't done it before on this dataset.
        if (!method %in% completed_normalizations()) {
            withProgress(message = "Pulling out all the stops", detail = "Step 3: Normalizing…", {
                full_df(info$fn(full_df()))
            })
            completed_normalizations(c(completed_normalizations(), method))
        }

        full_df(full_df() |>
                    mutate(F1_norm = .data[[paste0("F1", info$suffix)]],
                           F2_norm = .data[[paste0("F2", info$suffix)]]))
    })
    
    
    ### 2.2 Display data ----
    
    output$show_all_data <- DT::renderDataTable(DT::datatable({
        req(full_df())
        full_df() |>
            mutate(across(matches("F[1234]"), ~round(., 4)))
    }))
    
    ### 2.3 Splash screen ----
    output$splash <- renderUI({
        if (is.null(full_df())) {
            # Splash page
            div(style = "padding: 40px;",
                includeMarkdown("splash.md"))
        } else {
            # returns NULL when data is loaded, which renders nothing
        }
        
    })
    

    ### 2.4 Export data ----
    output$export_processed <- downloadHandler(
        filename = function() { "pipeline_output.csv" },
        content  = function(file) {
            full_df() |> write_csv(file = file)
        }
    )
    

    ### 2.5 Download plot ----
    output$fig_download <- downloadHandler(
        
        
        filename = function() { paste0(input$fig_filename, ".", tolower(input$fig_filetype)) },
        content = function(file) {
            req(full_df()) # require some data to prevent crashing
            ggsave(file,
                   plot   = generate_plot(),
                   height = input$fig_height,
                   width  = input$fig_width,
                   dpi    = input$fig_dpi,
                   device = ifelse(input$fig_filetype == "PDF", cairo_pdf, tolower(input$fig_filetype)))
        }
    )


    ## 3. Main plot ----
    
    midpoint_df_to_plot <- reactive({
        req(midpoints_df())
        midpoints_df() |> 
            filter(speaker_id %in% input$speaker_selection,
                   phoneme %in% input$vowels,
                   allophone_environment %in% input$environments)
    })
    # TODO: Trajectories
    # trajectories_df_to_plot <- reactive({
    #     req(trajectories_df())
    #     trajectories_df() |> 
    #         filter(speaker_id %in% input$speaker_selection,
    #                phoneme %in% input$vowels,
    #                allophone_environment %in% input$environments)
    # })
    vowel_space_df_for_hull <- reactive({
        req(midpoints_df())
        midpoints_df() |> 
            filter(speaker_id %in% input$speaker_selection,
                   allophone %in% c("BEET", "BIT", "BAIT", "BET", "BAT", "BOT", "BOUGHT", "BOAT", "PUT", "BOOT")) |>
            # Matches("F[1234]") intentionally catches both raw (F1, F2) and normalized (F1_lm, F2_z, etc.) columns.
            summarize(across(matches("F[1234]_norm"), \(x) mean(x, na.rm = TRUE)), .by = c(speaker_id, allophone))
    })

    
    
    # Named color vector covering every value of the color variable in the full
    # dataset. Passing this to scale_color_manual() keeps each vowel anchored to
    # the same color even when only a subset is displayed (persistence mode).

    # A function for generating the plot.
    generate_plot <- function() {
        
        # Security checks
        req(midpoint_df_to_plot())
        req(nrow(midpoint_df_to_plot()) > 0)
        
        ### Get the data. (Offloaded to reactive so it only reruns data prep if needed and not for small plot changes.)
        midpoint_df <- midpoint_df_to_plot()
        # TODO: Trajectories
        # trajectories_df <- trajectories_df_to_plot() 
        # Elsewhere allophones, for the hull
        vowel_space <- vowel_space_df_for_hull()

        # TODO: Trajectories
        # Get different summaries of the data for trajectories.
        # summarized_trajectories_df <- trajectories_df |> 
        #     mutate(plotting_group = token_id)
        # if (input$trajectory_type == "mean") {
        #     summarized_trajectories_df <- trajectories_df %>%
        #         group_by( %>%
        #         summarize(across(matches("F[1234]"), .fns = mean), .by = c(phoneme, allophone, prop_time))) %>%
        #         mutate(plotting_group = allophone)
        # } else if (input$trajectory_type == "median") {
        #     summarized_trajectories_df <- trajectories_df %>%
        #         summarize(across(matches("F[1234]"), .fns = median), .by = c(phoneme, allophone, prop_time)) %>%
        #         mutate(plotting_group = allophone)
        # } else if (input$trajectory_type == "smoothed") {
        #     summarized_trajectories_df <- trajectories_df %>%
        #         pivot_longer(cols = matches("F[1234]"), names_to = "formant", values_to = "hz") %>%
        #         group_by(phoneme, allophone, formant) %>%
        #         nest() %>%
        #         mutate(mdl = map(data, ~gam(hz ~ prop_time + s(prop_time, k = 4), data = .)),
        #                preds = map(mdl, ~get_predictions(., cond = list(prop_time = seq(0.2, 0.8, 0.01)),
        #                                                  print.summary = FALSE,
        #                                                  rm.ranef = FALSE))) %>%
        #         select(-data, -mdl) %>%
        #         unnest(preds) %>%
        #         rename(hz = fit) %>%
        #         select(-CI) %>%
        #         pivot_wider(names_from = formant, values_from = hz) %>%
        #         mutate(plotting_group = allophone)
        # }

        # TODO: Trajectories
        # Labels (mean for points, onset for trajectories)
        # if (input$show_trajectories & input$trajectory_type != "raw") {
        #     labels_df <- summarized_trajectories_df |> 
        #         filter(prop_time == min(prop_time))
        # } else{
            labels_df <- midpoint_df |>
                # Matches("F[1234]") intentionally catches both raw (F1, F2) and normalized (F1_lm, F2_z, etc.) columns.
                summarize(across(matches("F\\d_norm"), \(x) mean(x, na.rm = TRUE)), .by = c(phoneme, allophone))
        # }

        # Reference points
        reference_points <- vowel_space |>
            filter(speaker_id %in% input$speaker_selection,
                   allophone %in% c("BEET", "BOAT", "BOT", "BAT"))

        ### Basic elements 
        p <- ggplot(midpoint_df, aes(F2_norm, F1_norm))

        ### Optional elements 
        if (input$main_reference_points) {
            p <- p + geom_text(data = reference_points, aes(label = allophone), color = "gray20", size = 10)
        }
        if (input$main_vowel_space) {
            p <- p + geom_mark_hull(data = vowel_space, aes(group = 1), color = "gray20")
        }
        if (input$show_points) {
            p <- p + geom_point(aes(color = .data[[input$color_variable]]),
                                size = input$points_size, alpha = input$points_alpha)
        }
        if (input$show_ellipses) {
            p <- p + stat_ellipse(aes(group = .data[[input$ellipse_variable]], color = .data[[input$color_variable]]),
                                  level = input$ellipses_size/100, alpha = input$ellipses_alpha)
        }
        if (input$show_means) {
            p <- p +
                geom_text(data = labels_df,
                          aes(color = .data[[input$color_variable]], label = .data[[input$label_variable]]),
                          size = input$means_size, alpha = input$means_alpha)
        }
        if (input$show_ci) {
            ci_df <- midpoint_df |>
                summarize(
                    F1_mean = mean(F1_norm, na.rm = TRUE),
                    F2_mean = mean(F2_norm, na.rm = TRUE),
                    F1_se   = sd(F1_norm, na.rm = TRUE) / sqrt(n()),
                    F2_se   = sd(F2_norm, na.rm = TRUE) / sqrt(n()),
                    n       = n(),
                    .by = c(phoneme, allophone)
                ) |>
                mutate(
                    t_crit   = qt(0.975, n - 1),
                    F1_lower = F1_mean - t_crit * F1_se,
                    F1_upper = F1_mean + t_crit * F1_se,
                    F2_lower = F2_mean - t_crit * F2_se,
                    F2_upper = F2_mean + t_crit * F2_se
                )
            p <- p +
                geom_errorbar(data  = ci_df,
                              aes(x = F2_mean, y = F1_mean,
                                  ymin = F1_lower, ymax = F1_upper,
                                  color = .data[[input$color_variable]]),
                              orientation = "x",
                              width = 0, alpha = input$ci_alpha) +
                geom_errorbar(data = ci_df,
                              aes(x = F2_mean, y = F1_mean,
                                  
                                  xmin = F2_lower, xmax = F2_upper,
                                  color = .data[[input$color_variable]]),
                              orientation = "y",
                              width = 0, alpha = input$ci_alpha)
        }
        if (input$show_words) {
            p <- p + geom_text(aes(label = word,
                                   color = .data[[input$color_variable]]),
                               size = input$words_size, alpha = input$words_alpha)
        }
        # TODO: Trajectories
        # if (input$show_trajectories) {
        #     p <- p + geom_path(data = summarized_trajectories_df, 
        #                        aes(group = plotting_group, color = .data[[input$color_variable]]),
        #                        arrow = joey_arrow(), alpha = input$trajectories_alpha, linewidth = input$trajectories_size)
        # }
        # if (!is.na(input$trajectory_label_location)) {
        #   p <- p + geom_text(data = trajectory_labels_df,
        #                      aes(color = .data[[input$color_variable]], label = .data[[input$label_variable]]),
        #                      size = input$means_size, alpha = input$means_alpha)
        # }

        ### Color scale
        vis_values <- sort(unique(midpoint_df[[input$color_variable]]))
        p <- p + scale_color_manual(values = setNames(build_palette(length(vis_values), input$color_palette), vis_values))

        ### Final elements
        p <- p +
            scale_x_reverse() +
            scale_y_reverse() +
            labs(title    = if (nzchar(input$title))    input$title    else NULL,
                 subtitle = if (nzchar(input$subtitle)) input$subtitle else NULL,
                 x = input$x_label,
                 y = input$y_label) +
            theme_minimal(base_size = input$base_size, base_family = input$base_family) +
            theme(legend.position = if_else(input$show_legend, "right", "none"))

        p

    }
    # Render the main vowel plot as an image so that width, height, and res can
    # all be set together correctly. CSS dimensions use 96 DPI so the plot
    # occupies the right physical space on screen; the PNG is rendered at the
    # user-selected DPI and the browser scales it down for retina-like sharpness.
    # Note: generate_plot() is also used by the download handler (ggsave), which
    # is independent of these display dimensions.
    output$midpoints_plot <- renderImage(deleteFile = TRUE, {
        dpi  <- as.integer(input$plot_dpi)
        w_px <- as.integer(input$plot_width_in  * dpi)
        h_px <- as.integer(input$plot_height_in * dpi)

        tmpfile <- tempfile(fileext = ".png")
        png(tmpfile, width = w_px, height = h_px, res = dpi, units = "px")
        print(generate_plot())
        dev.off()

        list(src    = tmpfile,
             width  = as.integer(input$plot_width_in  * 96),
             height = as.integer(input$plot_height_in * 96),
             alt    = "Vowel plot")
    })



    ## 4. Acoustic Analysis----
    
    ### 4.1 Pillai scores ----
    #### Pillai data ----
    
    # Here's the dataset the Pillai scores are calculated on.
    pillai_df_raw <- reactive({
        req(midpoints_df())
        req(input$vowel_pair %in% names(vowel_pair_map))
        midpoints_df() |>
            filter(speaker_id %in% input$speaker_selection,
                   allophone %in% vowel_pair_map[[input$vowel_pair]],
                   !is.na(F1),
                   !is.na(F2))
    })
    # Check if there's enough data.
    pillai_valid <- reactive({
        
        # Make sure there is data
        req(pillai_df_raw())
        req(input$vowel_pair %in% names(vowel_pair_map))
        
        # Check both categories are present and have enough observations
        counts <- pillai_df_raw() |> count(allophone)
        
        if (nrow(counts) < 2) {
            list(valid = FALSE,
                 message = "Both vowels must be present in the data for the selected speaker(s).")
        } else if (any(counts$n < 5)) {
            list(valid = FALSE,
                 message = "Each vowel category needs at least 5 observations.")
        } else if (nrow(pillai_df_raw()) < 30) {
            list(valid = TRUE,
                 message = "Note: It is recommended that you have at least 30 observations.")
        } else {
            list(valid = TRUE, message = NULL)
        }
    })
    # Validation message — invisible when valid
    output$pillai_validation_message <- renderUI({
        req(pillai_valid()$message)  # only renders when invalid
        tags$p(pillai_valid()$message)
    })
    # Pillai data summary table (because it uses the _raw() data, it'll show regardless of how much data there is)
    output$pillai_pairs_summary <- renderTable({
        pillai_df_raw() |> 
            count(allophone, name = "number of tokens")
    })
    # A separate dataset that only exists if there's enough data.
    pillai_df <- reactive({
        req(pillai_valid()$valid)
        pillai_df_raw()
    })
    
    
    
    #### Pillai results ----
    
    # This one shows regardless of how much data there is.
    output$pillai_total_n <- renderText({
        nrow(pillai_df())
    })
    
    # For the remaining three, the numbers are NA if there isn't enough.
    output$pillai_threshold <- renderText({ 
        if (!pillai_valid()$valid) return("NA")
        round(exp(1)/(nrow(pillai_df())/2),3)
    })
    output$pillai_score <- renderText({ 
        if (!pillai_valid()$valid) return("NA")
        pillai_df() |> 
            summarize(pillai = pillai(cbind(F1_norm, F2_norm) ~ allophone)) |> 
            pull() |> 
            round(3)
    })
    output$pillai_p <- renderText({
        if (!pillai_valid()$valid) return("NA")
        p <- pillai_df() |> 
            summarize(p = manova_p(cbind(F1_norm, F2_norm) ~ allophone)) |> 
            pull()
        paste(ifelse(p < 0.001, "< 0.001", round(p, 3)))
    })
    

    #### Pillai plot ----
    
    output$vowel_pair_plot <- renderPlot({
        
        # Security checks
        req(pillai_valid()$valid)
        req(nrow(pillai_df_raw()) > 0)
        
        group_means <- pillai_df() |> 
            summarize(across(matches("F[1234]_norm"), mean), .by = allophone)
        
        # Elsewhere allophones, for the hull
        vowel_space <- vowel_space_df_for_hull()
        
        # Reference points
        reference_points <- vowel_space |>
            filter(allophone %in% c("BEET", "BOAT", "BOT", "BAT"))
        
        p <- ggplot(pillai_df_raw(), aes(F2_norm, F1_norm, color = allophone))

        if (input$pillai_reference_points) {
            p <- p + geom_text(data = reference_points, aes(label = allophone), color = "gray20", size = 10)
        }
        if (input$pillai_vowel_space) {
            p <- p + geom_mark_hull(data = vowel_space, aes(group = 1), color = "gray20")
        }

        p +
            geom_text(aes(label = word)) +
            stat_ellipse() +
            geom_text(data = group_means, aes(label = allophone), size = 10) +
            scale_color_manual(values = build_palette(2, input$color_palette)) +
            scale_x_reverse() +
            scale_y_reverse() +
            theme_minimal() +
            theme(legend.position = "none")
    })
}
